### ISSUE TITLE
Malformed Vdex file

### ISSUE THREAD

**Issue by russel5** [anestisb/vdexExtractor#40]
Hello. I'm have a problem with decompile com.sonymobile.settings.shakecontrol.vdex file on latest version of vdexextractor.

[ERROR] Verifier dependencies section points past the end of file (234 + c > 23d)
[ERROR] Malformed Vdex file
[ERROR] Failed to process Dex files - skipping 'framework/oat/arm64/com.sonymobile.settings.shakecontrol.vdex'

If i'm using version 0.4.1 all works, i can decompile this file and it work. I can deodex classes.dex from this file via baksmali.
Why latest version of vdexextractor show me that error?

**Comment by anestisb** [comment]
Should be fixed in https://github.com/anestisb/vdexExtractor/commit/99566f200d198530ba01f5e8a6318be4462c9953. Can you please check?

**Comment by russel5** [comment]
Yep, now all works. Thanks. Thread can be closed.

**Comment by russel5** [comment]
Sorry bro, but not fixed. Have another problem with another file
[ERROR] [11247] 2018/10/15 13:20:46 (jni/../src/vdex/vdex_006.c:168 vdex_006_SanityCheck) Verifier dependencies section points past the end of file (1d0 + 0 > 1d0)
[ERROR] [11247] 2018/10/15 13:20:46 (jni/../src/vdex/vdex_backend_006.c:340 vdex_backend_006_process) Malformed Vdex file
[ERROR] [11247] 2018/10/15 13:20:46 (jni/../src/vdexExtractor.c:257 main) Failed to process Dex files - skipping 'tcmiface.vdex'
I think 1d0 + 0 can be > that 1d0 :)
This file at the same place that previous

**Comment by anestisb** [comment]
Should be fixed in https://github.com/anestisb/vdexExtractor/commit/99566f200d198530ba01f5e8a6318be4462c9953. Can you check please?

**Comment by russel5** [comment]
Ok now, deodex full firmware - no more errors. Thanks.
